// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebEscuela.Repository.Data;

#nullable disable

namespace WebEscuela.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("WebEscuela.Repository.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuracionAnios")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreceptorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TituloOtorgado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PreceptorId");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.EstadoInscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstadosInscripcion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Aceptada"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Rechazada"
                        });
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Inscripcion", b =>
                {
                    b.Property<int>("AlumnoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MateriaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoInscripcionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("AlumnoId", "MateriaId");

                    b.HasIndex("EstadoInscripcionId");

                    b.HasIndex("MateriaId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarreraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocenteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("DocenteId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("TipoPersona").HasValue("Base");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorreoElectronico = "admin@escuela.com",
                            Dni = 12345678,
                            FechaNacimiento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Administrador Principal"
                        });
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Alumno"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Docente"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Preceptor"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Invitado"
                        });
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RolId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("RolId1");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contrasenia = "12345678",
                            CorreoElectronico = "admin@escuela.com",
                            Dni = 12345678,
                            PersonaId = 1,
                            RolId = 1
                        });
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Alumno", b =>
                {
                    b.HasBaseType("WebEscuela.Repository.Models.Persona");

                    b.Property<int>("CarreraId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CarreraId");

                    b.HasDiscriminator().HasValue("Alumno");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Docente", b =>
                {
                    b.HasBaseType("WebEscuela.Repository.Models.Persona");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Docente");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Carrera", b =>
                {
                    b.HasOne("WebEscuela.Repository.Models.Usuario", "Preceptor")
                        .WithMany()
                        .HasForeignKey("PreceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Preceptor");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Inscripcion", b =>
                {
                    b.HasOne("WebEscuela.Repository.Models.Alumno", "Alumno")
                        .WithMany("Inscripciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEscuela.Repository.Models.EstadoInscripcion", "EstadoInscripcion")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstadoInscripcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebEscuela.Repository.Models.Materia", "Materia")
                        .WithMany("Inscripciones")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("EstadoInscripcion");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Materia", b =>
                {
                    b.HasOne("WebEscuela.Repository.Models.Carrera", null)
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebEscuela.Repository.Models.Docente", "Docente")
                        .WithMany("Materias")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Usuario", b =>
                {
                    b.HasOne("WebEscuela.Repository.Models.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("WebEscuela.Repository.Models.Usuario", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebEscuela.Repository.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebEscuela.Repository.Models.Rol", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId1");

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Alumno", b =>
                {
                    b.HasOne("WebEscuela.Repository.Models.Carrera", null)
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.EstadoInscripcion", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Materia", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Persona", b =>
                {
                    b.Navigation("Usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Alumno", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("WebEscuela.Repository.Models.Docente", b =>
                {
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
